@include('front.home.sections.intro')
@include('front.home.sections.about')
@include('front.home.sections.articles')
@include('front.home.sections.requests')
@include('front.home.sections.contact')
@include('front.home.sections.app')
